### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by mhaseebkhan** [sdownie/refinerycms-demo#1]
@sdownie Cloned the code, created roles and assigned them to user. Still getting redirect loop.

``` ruby
#Create User Roles
Role.create(:title => 'Refinery')
Role.create(:title => 'Superuser')
#Assign user roles
user = User.first
user.roles << Role.find_by_title('Refinery')
user.roles << Role.find_by_title('Superuser')
user.save
```

**Comment by sdownie** [comment]
The redirect loop is a known issue with RefineryCMS.  It can be fixed by:
1) Upgrading RefineryCMSD
2) Adding a user to the database

Let me know if you think I should update the seed file with a default user.
